#==============================================================================
# ** Scene_Menu
#    Generated by RPG Maker XP Scene Engine PRO v6.0
#==============================================================================

class Scene_Menu
  #--------------------------------------------------------------------------
  # * Main Processing
  #--------------------------------------------------------------------------
  def main
    # Ì†ΩÌ≥ã @command_window (Window_Command)
    s_command_window = ["Item", "Skill", "Equip", "Status"]
    @command_window = Window_Command.new(160, s_command_window)

    # ‚è± @playtime_window (Window_PlayTime)
    @playtime_window = Window_PlayTime.new
    @playtime_window.y = 288

    # Ì†ΩÌ±£ @steps_window (Window_Steps)
    @steps_window = Window_Steps.new
    @steps_window.y = 352

    # Ì†ΩÌ≤∞ @gold_window (Window_Gold)
    @gold_window = Window_Gold.new
    @gold_window.y = 416

    # Ì†ΩÌ≥ã @status_window (Window_MenuStatus)
    @status_window = Window_MenuStatus.new
    @status_window.x = 160
    @status_window.active = false

    Graphics.transition

    # --- Main Loop ---
    loop do
      Graphics.update
      Input.update
      update
      break if $scene != self
    end

    Graphics.freeze

    # --- Dispose ---
    @command_window.dispose
    @playtime_window.dispose
    @steps_window.dispose
    @gold_window.dispose
    @status_window.dispose
  end

  #--------------------------------------------------------------------------
  # * Frame Update
  #--------------------------------------------------------------------------
  def update
    @command_window.update
    @playtime_window.update
    @steps_window.update
    @gold_window.update
    @status_window.update

    # Exit Key
    if Input.trigger?(Input::B)
      $game_system.se_play($data_system.cancel_se)
      $scene = Scene_Map.new
      return
    end
  end
end
